version: "3.7"

services:
    application:
        restart: on-failure
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: app-dev
        volumes:
            - ".:/app"
        ports:
            - '${PORT_PREFIX:-551}80:8000'
        env_file:
            - docker/dev.env
        environment:
            VIRTUAL_HOST: 'ietf.dev.springload.nz'
            VIRTUAL_PORT: 8000
        depends_on:
            - database
        networks:
            default:
                aliases:
                    - 'ietf.dev.springload.nz'
            nginx-proxy:

    frontend:
        restart: on-failure
        build:
            context: .
            dockerfile: docker/Dockerfile
            target: frontend
        volumes:
            - ".:/app"

    database:
        restart: on-failure
        image: postgres:11-alpine
        volumes:
            - "./docker/database:/docker-entrypoint-initdb.d/"
        ports:
            - '${PORT_PREFIX:-551}32:5432'
        environment:
            POSTGRES_DB: "app"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"

networks:
    nginx-proxy:
        external: true