[tool.pytest.ini_options]
addopts = "--reuse-db"
python_files = "ietf/*/test*.py"
filterwarnings = [
    "error",
    "ignore::DeprecationWarning:l18n.translation",
    "ignore:'index_together'.*'taggit.TaggedItem':django.utils.deprecation.RemovedInDjango51Warning:",
    "ignore::UserWarning",
]
