apiVersion: apps/v1
kind: Deployment
metadata:
  name: ietfweb
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ietfweb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ietfweb
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        # -----------------------------------------------------
        # ietfweb Container
        # -----------------------------------------------------
        - name: ietfweb
          image: "ghcr.io/ietf-tools/www:$APP_IMAGE_TAG"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          volumeMounts:
            - name: dt-vol
              mountPath: /a
            - name: www-tmp
              mountPath: /tmp
            - name: www-static
              mountPath: /app/static
            - name: www-media
              mountPath: /app/media
            - name: www-supervisor-cfg
              mountPath: /app/supervisord.conf
              subPath: supervisord.conf
            - name: www-cfg
              mountPath: /app/ietf/settings/local.py
              subPath: local.py
          env:
            - name: "CONTAINER_ROLE"
              value: "ietfweb"
          envFrom:
            - configMapRef:
                name: django-config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        # To be overriden with the actual shared volume
        - name: dt-vol
        - name: www-supervisor-cfg
          configMap:
            name: files-supervisor-cfg
        - name: www-tmp
          emptyDir:
            sizeLimit: "2Gi"
        - name: www-static
          emptyDir:
            sizeLimit: "2Gi"
        - name: www-media
        - name: www-cfg
          configMap:
            name: files-cfgmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ietfweb
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ietfweb
