namespace: ietfwww
namePrefix: ietfwww-
configMapGenerator:
  - name: files-cfgmap
    files:
      - local.py
      - supervisord.conf
resources:
  - django-config.yaml
  - memcached.yaml
  - wagtail.yaml
