{{- if .Values.serviceAccounts.wagtail.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wagtail.serviceAccountName.wagtail" . }}
  labels:
    {{- include "wagtail.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.wagtail.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
